export default {
    host: 'http://localhost:8080',
    // host: 'http://api.chuangshi.nowui.com',
    // action: 'system',
    is_menu: true,
    action: 'admin',
    platform: 'Admin',
    version: '9.9.9',
    page_size: 10,
    operation: '操作',
    search: '搜索',
    find: '查看',
    add: '新增',
    edit: '修改',
    del: '删除',
    load: '正在加载中..',
    success: '操作成功',
    error: '网络有问题',
    popconfirm_title: '您确定要删除该数据吗?',
    popconfirm_ok: '确定',
    popconfirm_cancel: '取消',
    required: '不能为空',
    placeholder: '请输入',
    detail_width: 1080,
    name: '广州市济颐馆贸易有限公司--总控后台',
    app_id: 'df2078d6c9eb46babb0df957127273ab',
    index: 'product/index',
    login: '/admin/login'
};
