export default {
	// host: 'http://localhost:8080',
	host: 'http://api.chuangshi.nowui.com',
	// action: 'system',
	action: 'admin',
	is_show_menu: true,
	platform: 'Admin',
	version: '1.0.0',
	page_size: 10,
	operation: '操作',
	search: '搜索',
	find: '查看',
	add: '新增',
	edit: '修改',
	del: '删除',
	load: '正在加载中..',
	success: '操作成功',
	error: '网络有问题',
	popconfirm_title: '您确定要删除该数据吗?',
	popconfirm_ok: '确定',
	popconfirm_cancel: '取消',
	required: '不能为空',
	placeholder: '请输入',
	detail_width: 1080,
	name: '统一--总控后台',
	app_id: 'd64666f02d7c4bf68a598076b88b81cf',
	index: '/uni/lottery/index',
	login: '/admin/login'
};
